Add BulkUpload class + Standard constraint
mjoerke/SpeziHealthKit pull request #1
Opened 2024-04-04 20:57 UTC by bryant-jimenez

# *Better Support for Batch Uploads of Historical HealthKit Data*

## :recycle: Current situation & Problem
*Link any open issues or pull requests (PRs) related to this PR. Please ensure that all non-trivial PRs are first tracked and discussed in an existing GitHub issue or discussion.*
- https://github.com/StanfordSpezi/SpeziHealthKit/issues/17

## :gear: Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented or links to the documentation if it appends or changes the public interface.*

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
*You can use this section to describe your solution, but we encourage contributors to document your reasoning and changes using in-line documentation.* 

## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov and that new functionality is appropriately tested.*
*This section describes important information about the tests and why some elements might not be testable.*

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2024-04-04 21:16 UTC, mjoerke requested changes
Thanks for the PR! Added some comments for improvements

2024-04-04 21:16 UTC, mjoerke commented on Package.swift
> +        .macOS(.v14)
Why are adding macOS?

2024-04-04 21:16 UTC, mjoerke commented on Sources/SpeziHealthKit/BulkUpload/BulkUpload.swift
>          predicate: NSPredicate? = nil,
Should the predicate be optional here? If we don't have a predicate, the default is to start from today, in which case we have no bulk upload?

2024-04-04 21:16 UTC, mjoerke commented on Sources/SpeziHealthKit/BulkUpload/BulkUploadSampleDataSource.swift
> +        if predicate == nil {
See comment above. Not sure if we want optional predicates here

2024-04-04 21:16 UTC, mjoerke commented on Sources/SpeziHealthKit/BulkUpload/BulkUploadSampleDataSource.swift
> +    let standard: any HealthKitConstraint
Do we need to add the BulkUploadConstraint here?

2024-04-04 21:16 UTC, mjoerke commented on Sources/SpeziHealthKit/BulkUpload/BulkUploadSampleDataSource.swift
> +            for deletedObject in result.deletedObjects {
This should use bulk processing from the standard rather than looping over individual add/remove calls

2024-04-04 21:16 UTC, bryant-jimenez commented on Sources/SpeziHealthKit/BulkUpload/BulkUploadSampleDataSource.swift
> +            for deletedObject in result.deletedObjects {
Yep realized that after i made the PR, fixed in most recent commit!

2024-04-04 21:32 UTC, bryant-jimenez commented on Package.swift
> +        .macOS(.v14)
Was giving me a weird build issue without it thats gone now - removed

2024-04-04 21:38 UTC, bryant-jimenez commented on Sources/SpeziHealthKit/BulkUpload/BulkUpload.swift
>          predicate: NSPredicate? = nil,
Good catch

2024-04-04 21:43 UTC, bryant-jimenez commented on Sources/SpeziHealthKit/BulkUpload/BulkUploadSampleDataSource.swift
> +    let standard: any HealthKitConstraint
<img width="1081" alt="image" src="https://github.com/mjoerke/SpeziHealthKit/assets/84168212/6f317f97-9921-4da5-905a-b9c072ad555f">

After going through and changing these references to the standard's type to BulkUploadConstraint, I then get an error that we arent conforming to HealthKitDataSourceDescription anymore in the overarching class - any idea how to fix? I thought the point of conforming to HealthKitDataSourceDescription was to use the existing protocol

<img width="879" alt="image" src="https://github.com/mjoerke/SpeziHealthKit/assets/84168212/f73e010b-de72-4a1f-926d-c7325c0e7e8d">

A potential fix might be to add a whole new protocol `BulkUploadDataSourceDescription` with its own function signature for `dataSources()`so that it expects a BulkUploadConstraint instead of HealthKitConstraint, thoughts? @mjoerke

2024-04-04 22:24 UTC, mjoerke commented on Sources/SpeziHealthKit/BulkUpload/BulkUploadSampleDataSource.swift
> +    let standard: any HealthKitConstraint
I see, I have a few ideas on how to address this. Let's ask Paul

2024-04-06 23:33 UTC, mjoerke approved these changes

2024-04-06 23:33 UTC, merged